base/urls.py
from django.urls import path

from . import views

app_name = 'base'

urlpatterns = [
    path('', views.index, name='index'),
    path('subjects/', views.SubjectView.as_view(), name='subjects'),
    path('addSubject/', views.CreateSubjectView.as_view(), name='addSubject'),
    path('subjects/<int:pk>/update', views.UpdateSubjectView.as_view(), name='subjectUpdate'),
    path('subjects/<int:pk>/delete', views.DeleteSubjectView.as_view(), name='subjectDelete'),
    path('administrator/', views.administrator, name='administrator'),
    path('student/', views.student, name='student'),
    path('teacher/', views.teacher, name='teacher'),
]

base/models.py
from django.db import models

# Create your models here.
class Subject(models.Model):
  subjectName = models.CharField(max_length=256)
  
  def __str__(self):
    return self.subjectName
  
class Book(models.Model):
  bookName = models.CharField(max_length=256)
  author = models.CharField(max_length = 256)
  isbn = models.CharField(max_length = 256)
  subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
  published = models.DateField()

base/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View

from .models import Subject

# Create your views here.
def index(request):
  
  return render(request, 'base/index.html')

class SubjectView(View):
  def get(self, request):
    subjects = Subject.objects.all()
    
    context = {
      'subjects': subjects,
    }
    
    return render(request, 'base/subject.html', context)

class CreateSubjectView(CreateView):
  model = Subject
  fields = '__all__'
  template_name = 'base/add_subject.html'
  success_url = reverse_lazy('base:subjects')
  
class UpdateSubjectView(UpdateView):
  model = Subject
  fields = '__all__'
  template_name = 'base/update_subject.html'
  success_url = reverse_lazy('base:subjects')
  
class DeleteSubjectView(DeleteView):
  model = Subject
  template_name = 'base/delete_subject.html'
  success_url = reverse_lazy('base:subjects')

def administrator(request):
  
  return render(request, 'base/admin_page.html')

def student(request):
  
  return render(request, 'base/student_page.html')

def teacher(request):
  
  return render(request, "base/teacher_page.html")

class BookView(View):
  pass

base/templates/base/add_subject.html
<h1>Add Subject</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_table }}
  <input type="submit" value="Add">
</form>

<p><a href="{% url 'base:index' %}">Back</a></p>

base/templates/base/admin_page.html
<h1>Admin Page</h1>

<p><a href="{% url 'base:subjects' %}">See Subjects</a></p>

<p><a href="{% url 'base:index' %}">Back</a></p>

base/templates/base/delete_subject.html
<h1>Delete Subject</h1>

<p>Are you sure you want to delete the subject: {{ subject }}</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, Delete.">
  <p><a href="{% url 'base:subjects' %}">Cancel</a></p>
</form>

base/templates/base/index.html
<h1>This is the home page</h1>
<p><a href="{% url 'base:administrator' %}">Go to Administrator Page</a></p>
<p><a href="{% url 'base:student' %}">Go to Student Page</a></p>
<p><a href="{% url 'base:teacher' %}">Go to Teacher Page</a></p>

base/templates/base/student_page.html
<h1>Student Page</h1>

<p><a href="{% url 'base:index' %}">Back</a></p>

base/templates/base/subject.html
<h1>Subjects</h1>

{% if subjects %}
<ul>
  {% for subject in subjects %}
    <li><a href="{% url 'base:books' %}"> {{ subject.subjectName }}</a> (
      <a href="{% url 'base:subjectUpdate' subject.id %}">Update</a> | 
      <a href="{% url 'base:subjectDelete' subject.id %}">Delete</a>)</li>
  {% endfor %}
</ul>
{% else %}
<p>There are no subjects in this library</p><br>
{% endif %}

<p><a href="{% url 'base:addSubject' %}">Add Subject</a></p>
<p><a href="{% url 'base:administrator' %}">Back</a></p>

base/templates/base/teacher_page.html
<h1>Teacher Page</h1>

<p><a href="{% url 'base:index' %}">Back</a></p>

base/templates/base/update_subject.html
<h1>Update Subject</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Update">
  <p><a href="{% url 'base:subjects' %}">Cancel</a></p>
</form>